#!/usr/bin/env bash

cd "${REPOSITORY_DIRECTORY}/colcon_ws" || exit 1

# Node type is either "python" or "cpp".
node_type="${1}"

# Get a list of packages defined in this workspace.
packages=$(colcon list --names-only)

for package in ${packages}; do
    executable_paths=$(ros2 pkg executables --full-path "${package}" 2>"/dev/null")

    for executable_path in ${executable_paths}; do
        # Filter out executables that do not match the specified node type.
        if [[ "${node_type}" == "python" && "${executable_path}" != *".py" ]]; then
            continue
        elif [[ "${node_type}" == "cpp"  && "${executable_path}" == *".py" ]]; then
            continue
        fi

        # Returned syntax has to be compatible with the vscode extension "augustocdias.tasks-shell-input".
        echo "${executable_path}|${package}/$(basename "${executable_path}")||" 
    done
done
