ARG PLATFORM

FROM rocm/dev-ubuntu-22.04 AS sfg-agent-devcontainer-amd
FROM ubuntu:22.04 AS sfg-agent-devcontainer-generic
FROM nvcr.io/nvidia/l4t-jetpack:r36.4.0 AS sfg-agent-devcontainer-nvidia-jetson
COPY ".devcontainer/dependencies/jetson_multimedia_api" "/usr/src/jetson_multimedia_api"
COPY ".devcontainer/dependencies/nvidia" "/usr/lib/aarch64-linux-gnu/tegra"
FROM nvidia/cuda:12.3.1-devel-ubuntu22.04 AS sfg-agent-devcontainer-nvidia
FROM rocm/dev-ubuntu-22.04 AS sfg-agent-devcontainer-steamdeck

FROM sfg-agent-devcontainer-${PLATFORM} AS sfg-agent-devcontainer

# Use bash as shell.
ENV SHELL=/bin/bash
SHELL ["/bin/bash", "-c"]
USER root

ARG PLATFORM
ENV PLATFORM=${PLATFORM}

ARG TZ=UTC
ENV TZ=${TZ}
RUN echo ${TZ} >"/etc/timezone"

ARG CONTAINER_WORKSPACE_DIRECTORY
ENV WORKSPACE_DIRECTORY=${CONTAINER_WORKSPACE_DIRECTORY}

ARG CONTAINER_REPOSITORY_MOUNT_POINT
ENV REPOSITORY_DIRECTORY=${CONTAINER_REPOSITORY_MOUNT_POINT}

#########################################################################################################
# Update and install required apt and pip dependencies.                                                 #
#########################################################################################################
RUN export DEBIAN_FRONTEND=noninteractive && \
    # Configure apt to use IPv4 because otherwise apt operations are slow as fuck!?
    echo 'Acquire::ForceIPv4 "true";' >"/etc/apt/apt.conf.d/99-force-ipv4" && \
    apt update && apt upgrade -y && apt install -y --no-install-recommends \
        bmon \
        build-essential \
        cmake \
        curl \
        dotnet-sdk-6.0 \
        gdb \
        git-lfs \
        iproute2 \
        iperf3 \
        libudev-dev \
        libusb-1.0-0-dev \
        nano \
        net-tools \
        pkg-config \
        python-is-python3 \
        python3 \
        python3-pip \
        ssh-client \
        sudo \
        tzdata \
        usbutils && \
    apt -y autoremove && apt clean && rm -rf "/var/lib/apt/lists/"*

# Install ffmpeg.
RUN apt update && \
    # On nvidia-jetson we need to install a patched version of ffmpeg to support the Jetson's video encoding/decoding capabilities.
    if [[ ${PLATFORM} == "nvidia-jetson" ]]; then \
        # The nvidia-jetson base image we use comes with an NVIDIA accelerated version of OpenCV. In theory this is good, but in practice it
        # seems to be ABI incompatible with ffmpeg_image_transport and causes issues. Therefore we uninstall it and install the standard Ubuntu OpenCV version.
        apt-get purge -y \
            libopencv* \
            nvidia-opencv* \ 
            opencv-* && \
        apt-get install -y --no-install-recommends --allow-downgrades \
            libopencv-dev=4.5.4+dfsg-9ubuntu4 \
            python3-opencv=4.5.4+dfsg-9ubuntu4 && \
        \
        mkdir -p "${HOME}/dependencies" && cd "${HOME}/dependencies" && \
        # Install ffmpeg.
        git clone -b "master" --depth 1 "https://github.com/berndpfrommer/jetson-ffmpeg.git" && \
        cd "jetson-ffmpeg" && \
        mkdir "build" && cd "build" && \
        cmake -DCMAKE_INSTALL_PREFIX:PATH="/usr/local" ".." && make -j$(nproc) && make install && ldconfig && \
        cd "../.." && \
        git clone -b "release/7.1" --depth 1 "git://source.ffmpeg.org/ffmpeg.git" && \
        cd "jetson-ffmpeg" && \
        "./ffpatch.sh" "../ffmpeg" && \
        cd "../ffmpeg" && \
        PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:${PKG_CONFIG_PATH}" "./configure" --enable-nvmpi --enable-shared --disable-static --prefix="/usr/local" && \
        make -j$(nproc) && \
        make install && \
        ldconfig && \
        rm -rf "${HOME}/dependencies"; \
    else \
        apt install -y --no-install-recommends \
            ffmpeg \
            libavcodec58 \
            libavfilter7 \
            libavformat58 \
            libavutil56 \
            libpostproc55 \
            libswscale5 \
            libswresample3; \
    fi && \
    \
    apt -y autoremove && apt clean && rm -rf "/var/lib/apt/lists/"*

RUN pip install --upgrade \
        pybind11[global] \
        pybind11-stubgen && \
    \
    if [[ ${PLATFORM} == "nvidia-jetson" ]]; then \
        pip install \
            jetson-stats; \
    fi

#########################################################################################################
# Create a non-root user.                                                                               #
#########################################################################################################
ARG USERNAME=developer
ENV USERNAME=${USERNAME}
ARG USER_UID=1000
ARG USER_GID=${USER_UID}
ENV HOME=/home/${USERNAME}

RUN if [ ! $(getent group "${USER_GID}") ]; then \
        groupadd --gid "${USER_GID}" "${USERNAME}" &>"/dev/null"; \
    else \
        CONFLICTING_GROUPNAME=`getent group "${USER_GID}" | cut -d: -f1` && \
        groupmod -o --gid "${USER_GID}" -n "${USERNAME}" "${CONFLICTING_GROUPNAME}"; \
    fi && \
    \
    if [ ! $(getent passwd "${USER_UID}") ]; then \
        useradd --no-log-init --uid "${USER_UID}" --gid "${USER_GID}" -m "${USERNAME}" &>"/dev/null"; \
    else \
        CONFLICTING_USERNAME=`getent passwd "${USER_UID}" | cut -d: -f1` && \
        usermod -l "${USERNAME}" -u "${USER_UID}" -m -d "/home/${USERNAME}" "${CONFLICTING_USERNAME}" &>"/dev/null" && \
        mkdir -p "/home/${USERNAME}" && \
        # Wipe files that may create issues for users with large UID numbers.
        rm -f "/var/log/lastlog /var/log/faillog"; \
    fi && \
    \
    chown "${USERNAME}":"${USERNAME}" "/home/${USERNAME}" && \
    echo "${USERNAME}" ALL=\(root\) NOPASSWD:ALL >"/etc/sudoers.d/${USERNAME}" && \
    chmod 0440 "/etc/sudoers.d/${USERNAME}" && \
    usermod -aG video,plugdev,sudo "${USERNAME}"

# Activate the previously created user.
USER ${USERNAME}
# Set our working directory.
WORKDIR ${CONTAINER_WORKSPACE_DIRECTORY}
# Ensure we can read/write to the working directory.
RUN sudo chown "${USERNAME}":"${USERNAME}" "." && \
    # Fix for empty .bashrc and non-existing .profile when on nvidia platform.
    [[ ${PLATFORM} == "nvidia" ]] && cat "/etc/skel/.bashrc" >>"/home/${USERNAME}/.bashrc" && cat "/etc/skel/.profile" >>"/home/${USERNAME}/.profile" || true

#########################################################################################################
# Setup ROS2.                                                                                           #
#########################################################################################################
COPY --chown=${USERNAME}:${USERNAME} ".devcontainer/.vscode" "${CONTAINER_WORKSPACE_DIRECTORY}/.vscode"

ENV LANG=en_US.UTF-8
ENV RMW_IMPLEMENTATION=rmw_fastrtps_cpp
ENV COLCON_WS=${CONTAINER_REPOSITORY_MOUNT_POINT}/colcon_ws
ENV ROS_DISTRO=humble

RUN --mount=type=bind,source=".devcontainer/config",target="/tmp/config",ro \
    sudo apt update && sudo apt install -y --no-install-recommends \
        locales \
        software-properties-common && \
    sudo apt -y autoremove && sudo apt clean && sudo rm -rf "/var/lib/apt/lists/"* && \
    \
    sudo locale-gen ${LANG} && \
    sudo update-locale LC_ALL=${LANG} LANG=${LANG} && \
    sudo add-apt-repository -y universe && \
    export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F\" '{print $4}') && \
    curl -L -o "/tmp/ros2-apt-source.deb" "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo ${UBUNTU_CODENAME:-${VERSION_CODENAME}})_all.deb" && \
    sudo dpkg -i "/tmp/ros2-apt-source.deb" && \
    sudo apt update && sudo apt install -y --no-install-recommends \
        debhelper \
        fakeroot \
        python3-colcon-mixin \
        ros-${ROS_DISTRO}-diagnostic-updater \
        ros-${ROS_DISTRO}-magic-enum \
        ros-${ROS_DISTRO}-ros-base \
        ros-${ROS_DISTRO}-xacro \
        ros-dev-tools && \
    sudo apt -y autoremove && sudo apt clean && sudo rm -rf "/var/lib/apt/lists/"* && \
    sudo rosdep init && \
    colcon mixin add default "https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml" && \
    colcon mixin update default && \
    echo "source /opt/ros/${ROS_DISTRO}/setup.bash" | sudo tee -a "/etc/bash.bashrc" && \
    echo "[ -f ${COLCON_WS}/install/setup.bash ] && source ${COLCON_WS}/install/setup.bash" | sudo tee -a "/etc/bash.bashrc" && \
    cp "/tmp/config/colcon_defaults.yaml" "${HOME}/.colcon/defaults.yaml"

# Install ffmpeg_image_transport.
RUN mkdir -p "${HOME}/dependencies/colcon_ws/src" && cd "${HOME}/dependencies/colcon_ws/src" && \
    git clone -b "3.0.2" --depth 1 "https://github.com/ros-misc-utilities/ffmpeg_image_transport.git" && \
    cd ".." && \
    vcs import <"src/ffmpeg_image_transport/ffmpeg_image_transport.repos" && \
    source "/opt/ros/${ROS_DISTRO}/setup.bash" && \
    sudo apt update && rosdep update && sudo -E rosdep install -y --from-paths "." --ignore-src && \
    cd "src" && \
    \
    for package in "ffmpeg_encoder_decoder" "ffmpeg_image_transport_msgs" "ffmpeg_image_transport"; do \
        cd "${package}" && \
        # Generate debian files.
        bloom-generate rosdebian && \
        # Disable building tests and treat deprecation warnings as non-fatal.
        sed -i 's/dh_auto_configure --/dh_auto_configure -- -DBUILD_TESTING=OFF -DCMAKE_CXX_FLAGS="-Wno-error=deprecated-declarations"/g' "debian/rules" && \
        # Use all cores for building.
        sed -i 's/\bdh_auto_build\b/& -- -j$(nproc)/g' "debian/rules" && \
        # Ignore missing info for shlibdeps.
        sed -i 's/dh_shlibdeps -/dh_shlibdeps --dpkg-shlibdeps-params=--ignore-missing-info -/g' "debian/rules" && \
        # Build the package.
        fakeroot "debian/rules" binary && \
        # Install the package.
        cd ".." && sudo apt install -y "./"*".deb" && rm "./"*".deb"; \
    done && \
    \
    rm -rf "${HOME}/dependencies" && \
    sudo rm -rf "${HOME}/.ros/rosdep/"* && \
    sudo apt -y autoremove && sudo apt clean && sudo rm -rf "/var/lib/apt/lists/"*

# Install a backport of jazzy's compressed_depth_image_transport to make RVL compression available.
RUN mkdir -p "${HOME}/dependencies" && cd "${HOME}/dependencies" && \
    mkdir -p "${HOME}/dependencies/colcon_ws/src" && cd "${HOME}/dependencies/colcon_ws/src" && \
    git clone -b "humble-backport" --depth 1 "https://gitlab+deploy-token-29:gldt-rYgXc6pABSLKuWS82qpJ@gitlab.hs-esslingen.de/smart-factory-grids/autonomous-systems/tools/image-transport-plugins-humble-backport.git" "image_transport_plugins_humble_backport" && \
    cd ".." && \
    source "/opt/ros/${ROS_DISTRO}/setup.bash" && \
    rosdep update && \
    cd "src/image_transport_plugins_humble_backport" && \
    \
    for package in "compressed_depth_image_transport"; do \
        cd "${package}" && \
        # Generate debian files.
        bloom-generate rosdebian && \
        # Use all cores for building.
        sed -i 's/\bdh_auto_build\b/& -- -j$(nproc)/g' "debian/rules" && \
        # Ignore missing info for shlibdeps.
        sed -i 's/dh_shlibdeps -/dh_shlibdeps --dpkg-shlibdeps-params=--ignore-missing-info -/g' "debian/rules" && \
        # Build the package.
        fakeroot "debian/rules" binary && \
        # Install the package.
        cd ".." && sudo apt install -y "./"*".deb" && rm "./"*".deb"; \
    done && \
    \
    rm -rf "${HOME}/dependencies" && \
    sudo rm -rf "${HOME}/.ros/rosdep/"*

#########################################################################################################
# Apply patches.                                                                                        #
#########################################################################################################
WORKDIR /

RUN --mount=type=bind,source=".devcontainer/patches",target="/tmp/patches",ro \
    # Apply general patches.
    for PATCH in "/tmp/patches/"*".patch"; do \
        # Check if the patch file actually exists (glob might return the pattern if no files match).
        [ -f "${PATCH}" ] || continue; \
        sudo patch -p1 --forward <"${PATCH}"; \
    done && \
    # Apply platform specific patches.
    for PATCH in "/tmp/patches/${PLATFORM}/"*".patch"; do \
        [ -f "${PATCH}" ] || continue; \
        sudo patch -p1 --forward <"${PATCH}"; \
    done

#########################################################################################################
# User dockerfile will be inserted below.                                                               #
#########################################################################################################
# :DOCKERFILE_USER:
