FROM ros:kilted-ros-core-noble

# Use bash as shell.
ENV SHELL=/bin/bash
SHELL ["/bin/bash", "-c"]
USER root

#########################################################################################################
# Update and install required apt-get and pip dependencies.                                             #
#########################################################################################################
ENV ROS_DISTRO=kilted

RUN apt-get update && apt-get upgrade -y && apt-get install -y --no-install-recommends \
        build-essential \
        git \
        python3-pip \
        ros-${ROS_DISTRO}-rmw-zenoh-cpp && \
    apt-get -y autoremove && apt-get clean && rm -rf "/var/lib/apt/lists/"*

RUN git clone -b "${ROS_DISTRO}" --depth 1 "https://github.com/sfg-autonomous-systems/sfg_zenoh_domain_bridge.git" && \
    cd "sfg_zenoh_domain_bridge" && \
    pip install --break-system-packages .

COPY .devcontainer/scripts/cross_domain_router_entrypoint /entrypoint
ENTRYPOINT ["/entrypoint"]
CMD ["-l", "debug"]