mode: router

scouting:
  multicast:
    enabled: true
    autoconnect:
      router:
        - router

access_control:
  enabled: true
  default_permission: deny
  rules:
    - id: local
      messages:
        [
          "put",
          "declare_subscriber",
          "query",
          "declare_queryable",
          "liveliness_token",
          "declare_liveliness_subscriber",
        ]
      permission: allow
      key_exprs: ["**"]
    - id: global
      messages:
        [
          "put",
          "declare_subscriber",
          "query",
          "declare_queryable",
          "liveliness_token",
          "declare_liveliness_subscriber",
        ]
      permission: allow
      key_exprs:
        - "*/*/global/**"
        - "*/*/tf/**"
        - "*/*/tf_static/**"
        - "*/*/ros_discovery_info/**"
  subjects:
    - id: local
      interfaces: ["lo"]
    - id: global
  policies:
    - id: local
      rules: ["local"]
      subjects: ["local"]
    - id: global
      rules: ["global"]
      subjects: ["global"]
