include:
  - path:
      - "./compose.isaac_ros.base.yaml"
      - "./compose.isaac_ros.${PLATFORM}.yaml"
      - "../../.devcontainer-user/compose.yaml"
    env_file:
      - "./.env"
  - path:
      - "../dependencies/fast_dds_router/.devcontainer/compose/compose.fast_dds_router.yaml"
    env_file:
      - "../dependencies/fast_dds_router/.devcontainer/compose/.env"
