services:
  isaac_ros:
    build:
      context: "../.."
      dockerfile: ".devcontainer/docker/dockerfile.isaac_ros"
      args:
        - PLATFORM=${PLATFORM}
        - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
        - CONTAINER_WORKSPACE_DIRECTORY=${CONTAINER_WORKSPACE_DIRECTORY}
        - CONTAINER_REPOSITORY_MOUNT_POINT=${CONTAINER_REPOSITORY_MOUNT_POINT}
        - USERNAME=${LOCAL_USERNAME}
        - USER_UID=${LOCAL_USER_UID}
        - USER_GID=${LOCAL_USER_GID}
    restart: unless-stopped
    volumes:
      - type: bind
        source: "../.."
        target: "${CONTAINER_REPOSITORY_MOUNT_POINT}"
      - type: bind
        source: "${LOCAL_SELECTED_DIRECTORY}"
        target: "${CONTAINER_SELECTED_DIRECTORY_MOUNT_POINT}"
      - type: bind
        source: "/dev"
        target: "/dev"
      - type: bind
        source: "/etc/timezone"
        target: "/etc/timezone"
        read_only: true
      - type: bind
        source: "/etc/localtime"
        target: "/etc/localtime"
        read_only: true
    environment:
      - DISPLAY
      - NVIDIA_DRIVER_CAPABILITIES=all
    network_mode: host
    privileged: true
    ipc: host
    runtime: nvidia
