services:
  container:
    build:
      context: "${LOCAL_WORKSPACE_DIRECTORY}"
      dockerfile: ".devcontainer/dockerfile"
      args:
        - PLATFORM=${PLATFORM}
        - CONTAINER_REPOSITORY_MOUNT_POINT=${CONTAINER_REPOSITORY_MOUNT_POINT}
        - CONTAINER_WORKSPACE_DIRECTORY=${CONTAINER_WORKSPACE_DIRECTORY}
        - LOCAL_DEVCONTAINER_USER_DIRECTORY=${LOCAL_DEVCONTAINER_USER_DIRECTORY}
        - USERNAME=${USERNAME}
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
    volumes:
      - type: bind
        source: "${LOCAL_WORKSPACE_DIRECTORY}"
        target: "${CONTAINER_REPOSITORY_MOUNT_POINT}"
      - type: bind
        source: "${SELECTED_DIRECTORY}"
        target: "${CONTAINER_SELECTED_DIRECTORY_MOUNT_POINT}"
      - type: bind
        source: "/dev"
        target: "/dev"
      - type: bind
        source: "/etc/localtime"
        target: "/etc/localtime"
        read_only: true
    environment:
      - WORKSPACE_DIRECTORY=${CONTAINER_WORKSPACE_DIRECTORY}
      - REPOSITORY_DIRECTORY=${CONTAINER_REPOSITORY_MOUNT_POINT}
      - DEVCONTAINER_USER_DIRECTORY=${CONTAINER_DEVCONTAINER_USER_DIRECTORY}
      - NVIDIA_DRIVER_CAPABILITIES=all
    network_mode: host
    privileged: true
    ipc: host
    runtime: nvidia
