
ARG PLATFORM=arm64

FROM --platform=arm64 ros:humble-perception-jammy AS sfg-agent-devcontainer-arm64
COPY ".devcontainer/dependencies/jetson_multimedia_api" "/usr/src/jetson_multimedia_api"
COPY ".devcontainer/dependencies/nvidia" "/usr/lib/aarch64-linux-gnu/tegra"

FROM --platform=amd64 ros:humble-perception-jammy AS sfg-agent-devcontainer-amd64
FROM sfg-agent-devcontainer-${PLATFORM} AS sfg-agent-devcontainer

# Use bash as shell.
ENV SHELL=/bin/bash
SHELL ["/bin/bash", "-c"]

ARG PLATFORM=arm64
ENV PLATFORM=${PLATFORM}

ARG ROS_DOMAIN_ID
ENV ROS_DOMAIN_ID=${ROS_DOMAIN_ID}

ARG CONTAINER_WORKSPACE_DIRECTORY
ENV WORKSPACE_DIRECTORY=${CONTAINER_WORKSPACE_DIRECTORY}

ARG CONTAINER_REPOSITORY_MOUNT_POINT
ENV REPOSITORY_DIRECTORY=${CONTAINER_REPOSITORY_MOUNT_POINT}

USER root

#########################################################################################################
# Update and install required apt and pip dependencies.                                                 #
#########################################################################################################
RUN --mount=type=cache,id=apt_cache_devcontainer,target="/var/cache/apt" \
    apt update && apt install -y --no-install-recommends \
        libudev-dev \
        debhelper \
        fakeroot \
        ninja-build \
        git-lfs \
        net-tools \
        nano \
        iproute2 \
        iperf3 \
        bmon \
        usbutils \
        gdb \
        python3-dev\
        python3-pip \
        python3-bloom \
        python-is-python3 \
        dotnet-sdk-6.0 && \
    apt -y autoremove && apt clean && rm -rf "/var/lib/apt/lists/"*

RUN pip install --upgrade \
        pybind11[global] \
        pybind11-stubgen && \
        \
        if [[ ${PLATFORM} == "arm64" ]]; then \
            pip install \ 
                jetson-stats; \
        fi

#########################################################################################################
# Apply patches.                                                                                        #
#########################################################################################################
WORKDIR /

RUN --mount=type=bind,source=".devcontainer/patches",target="/tmp/patches",ro \
    # Apply general patches.
    for PATCH in "/tmp/patches/"*".patch"; do \
        # Check if the patch file actually exists (glob might return the pattern if no files match
        [ -f "${PATCH}" ] || continue; \
        patch -p1 --forward <"${PATCH}"; \
    done && \
    # Apply platform specific patches.
    for PATCH in "/tmp/patches/${PLATFORM}/"*".patch"; do \
        [ -f "${PATCH}" ] || continue; \
        patch -p1 --forward <"${PATCH}"; \
    done

#########################################################################################################
# Create a non-root user.                                                                               #
#########################################################################################################
ARG USERNAME=developer
ENV USERNAME=${USERNAME}
ARG USER_UID=1000
ARG USER_GID=${USER_UID}
ENV HOME=/home/${USERNAME}

RUN if [ ! $(getent group "${USER_GID}") ]; then \
        groupadd --gid "${USER_GID}" "${USERNAME}" &>"/dev/null"; \
    else \
        CONFLICTING_GROUPNAME=`getent group "${USER_GID}" | cut -d: -f1` && \
        groupmod -o --gid "${USER_GID}" -n "${USERNAME}" "${CONFLICTING_GROUPNAME}"; \
    fi && \
    \
    if [ ! $(getent passwd "${USER_UID}") ]; then \
        useradd --no-log-init --uid "${USER_UID}" --gid "${USER_GID}" -m "${USERNAME}" &>"/dev/null"; \
    else \
        CONFLICTING_USERNAME=`getent passwd "${USER_UID}" | cut -d: -f1` && \
        usermod -l "${USERNAME}" -u "${USER_UID}" -m -d "/home/${USERNAME}" "${CONFLICTING_USERNAME}" &>"/dev/null" && \
        mkdir -p "/home/${USERNAME}" && \
        # Wipe files that may create issues for users with large UID numbers.
        rm -f "/var/log/lastlog /var/log/faillog"; \
    fi && \
    \
    chown "${USERNAME}":"${USERNAME}" "/home/${USERNAME}" && \
    echo "${USERNAME}" ALL=\(root\) NOPASSWD:ALL >"/etc/sudoers.d/${USERNAME}" && \
    chmod 0440 "/etc/sudoers.d/${USERNAME}" && \
    usermod -aG video,plugdev,sudo "${USERNAME}"

# Activate the previously created user.
USER ${USERNAME}
# Set our working directory.
WORKDIR ${CONTAINER_WORKSPACE_DIRECTORY}
# Ensure we can read/write to the working directory.
RUN sudo chown "${USERNAME}":"${USERNAME}" "."

#########################################################################################################
# Setup ROS2.                                                                                           #
#########################################################################################################
COPY --chown=${USERNAME}:${USERNAME} ".devcontainer/.vscode" "${CONTAINER_WORKSPACE_DIRECTORY}/.vscode"

ENV RMW_IMPLEMENTATION=rmw_fastrtps_cpp

# Install ffmpeg_image_transport.
RUN sudo apt update && \
    # On arm64 we need to install a patched version of ffmpeg to support the Jetson's video encoding/decoding capabilities.
    if [[ ${PLATFORM} == "arm64" ]]; then \
        mkdir -p "${HOME}/dependencies" && cd "${HOME}/dependencies" && \
        # Install ffmpeg.
        git clone -b "master" --depth 1 "https://github.com/berndpfrommer/jetson-ffmpeg.git" && \
        cd "jetson-ffmpeg" && \
        mkdir "build" && cd "build" && \
        cmake -DCMAKE_INSTALL_PREFIX:PATH="/usr/local" ".." && make -j$(nproc) && sudo make install && sudo ldconfig && \
        cd "../.." && \
        git clone -b "release/7.1" --depth 1 "git://source.ffmpeg.org/ffmpeg.git" && \
        cd "jetson-ffmpeg" && \
        "./ffpatch.sh" "../ffmpeg" && \
        cd "../ffmpeg" && \
        "./configure" --enable-nvmpi --enable-shared --disable-static --prefix="/usr/local" && \
        make -j$(nproc) && \
        sudo make install && \
        sudo ldconfig && \
        sudo rm -rf "${HOME}/dependencies"; \
    else \
        sudo apt install -y --no-install-recommends \
            ffmpeg \
            libavcodec58 \
            libavformat58 \
            libavutil56 \
            libswscale5 \
            libswresample3 \
            libavfilter7 \
            libpostproc55; \
    fi && \
    \
    mkdir -p "${HOME}/dependencies/colcon_ws/src" && cd "${HOME}/dependencies/colcon_ws/src" && \
    git clone -b "3.0.2" --depth 1 "https://github.com/ros-misc-utilities/ffmpeg_image_transport.git" && \
    cd ".." && \
    vcs import <"src/ffmpeg_image_transport/ffmpeg_image_transport.repos" && \
    source "/opt/ros/${ROS_DISTRO}/setup.bash" && \
    rosdep update && sudo rosdep install -y --from-paths "." --ignore-src && \
    cd "src" && \
    \
    for package in "ffmpeg_encoder_decoder" "ffmpeg_image_transport_msgs" "ffmpeg_image_transport"; do \
        cd "${package}" && \
        # Generate debian files.
        bloom-generate rosdebian && \
        # Disable building tests and treat deprecation warnings as non-fatal.
        sed -i 's/dh_auto_configure --/dh_auto_configure -- -DBUILD_TESTING=OFF -DCMAKE_CXX_FLAGS="-Wno-error=deprecated-declarations"/g' "debian/rules" && \
        # Use all cores for building.
        sed -i 's/\bdh_auto_build\b/& -- -j$(nproc)/g' "debian/rules" && \
        # Ignore missing info for shlibdeps.
        sed -i 's/dh_shlibdeps -/dh_shlibdeps --dpkg-shlibdeps-params=--ignore-missing-info -/g' "debian/rules" && \
        # Build the package.
        fakeroot "debian/rules" binary && \
        # Install the package.
        cd ".." && sudo apt install -y "./"*".deb" && rm "./"*".deb"; \
    done && \
    \
    rm -rf "${HOME}/dependencies" && \
    sudo rm -rf "${HOME}/.ros/rosdep/"* && \
    sudo apt -y autoremove && sudo apt clean && sudo rm -rf "/var/lib/apt/lists/"*

# Install a backport of jazzy's compressed_depth_image_transport to make RVL compression available.
RUN mkdir -p "${HOME}/dependencies" && cd "${HOME}/dependencies" && \
    mkdir -p "${HOME}/dependencies/colcon_ws/src" && cd "${HOME}/dependencies/colcon_ws/src" && \
    git clone -b "humble-backport" --depth 1 "https://gitlab+deploy-token-29:gldt-rYgXc6pABSLKuWS82qpJ@gitlab.hs-esslingen.de/smart-factory-grids/autonomous-systems/tools/image-transport-plugins-humble-backport.git" "image_transport_plugins_humble_backport" && \
    cd ".." && \
    source "/opt/ros/${ROS_DISTRO}/setup.bash" && \
    rosdep update && \
    cd "src/image_transport_plugins_humble_backport" && \
    \
    for package in "compressed_depth_image_transport"; do \
        cd "${package}" && \
        # Generate debian files.
        bloom-generate rosdebian && \
        # Use all cores for building.
        sed -i 's/\bdh_auto_build\b/& -- -j$(nproc)/g' "debian/rules" && \
        # Build the package.
        fakeroot "debian/rules" binary && \
        # Install the package.
        cd ".." && sudo apt install -y "./"*".deb" && rm "./"*".deb"; \
    done && \
    \
    rm -rf "${HOME}/dependencies" && \
    sudo rm -rf "${HOME}/.ros/rosdep/"*

RUN --mount=type=cache,id=apt_cache_devcontainer,target="/var/cache/apt" \
    sudo apt update && sudo apt install -y --no-install-recommends \
        ros-${ROS_DISTRO}-magic-enum \
        ros-${ROS_DISTRO}-xacro \
        python3-colcon-mixin && \
    sudo apt -y autoremove && sudo apt clean && sudo rm -rf "/var/lib/apt/lists/"* && \
    \
    colcon mixin add default "https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml" && \
    colcon mixin update default && \
    echo "[ -f ${CONTAINER_REPOSITORY_MOUNT_POINT}/colcon_ws/install/setup.bash ] && source ${CONTAINER_REPOSITORY_MOUNT_POINT}/colcon_ws/install/setup.bash" | sudo tee -a "/etc/bash.bashrc"

COPY ".devcontainer/config/colcon_defaults.yaml" "${HOME}/.colcon/defaults.yaml"

#########################################################################################################
# User dockerfile will be inserted below.                                                               #
#########################################################################################################
# :DOCKERFILE_USER: