#!/usr/bin/env bash

build_isaac_ros_base_image() {
    local START_TEXT="> Building Isaac ROS base image."
    local END_TEXT="< Done building Isaac ROS base image."

    print_info "${START_TEXT}"
    local image_key=""

    case $(uname -m) in
    "x86_64")
        image_key="x86_64"
        ;;

    "aarch64" | "arm64")
        image_key="aarch64"
        ;;
    esac

    "${SCRIPT_DIR}/../build_dependencies/isaac_ros_common/scripts/build_image_layers.sh" \
        --image_key "${image_key} ros2_humble" \
        --image_name "isaac-ros-base"

    print_info "${END_TEXT}"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)
    source "${SCRIPT_DIR}/common"
    build_isaac_ros_base_image "${@}"
fi
