#!/usr/bin/env bash

sfg_isaac_ros_devcontainer__build_isaac_ros_image() {
    local SCRIPT_DIR
    SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)"
    source "${SCRIPT_DIR}/bash_utils/common"

    local START_TEXT="> Building Isaac ROS base image."
    local END_TEXT="< Done building Isaac ROS base image."

    sfg_bash_utils__print_info "${START_TEXT}"
    local architecture=""

    case $(uname -m) in
    "x86_64")
        architecture="x86_64"
        ;;

    "aarch64" | "arm64")
        architecture="aarch64"
        ;;
    esac

    # Build the Isaac ROS base image but ignore errors because (1) because if we do not have
    # an internet connection the build will fail and (2) any failure to build the base image
    # will be caught later when we try to build the actual user image.
    "${SCRIPT_DIR}/../dependencies/isaac_ros_common/scripts/build_image_layers.sh" \
        --image_key "${architecture}.ros2_humble" \
        --image_name "isaac-ros" || true

    sfg_bash_utils__print_info "${END_TEXT}"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    set -e
    sfg_isaac_ros_devcontainer__build_isaac_ros_image "${@}"
fi
