#!/usr/bin/env bash

sfg_isaac_ros_devcontainer__build_isaac_ros_base_image() {
    local SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)
    source "${SCRIPT_DIR}/bash_utils/common"

    local START_TEXT="> Building Isaac ROS base image."
    local END_TEXT="< Done building Isaac ROS base image."

    sfg_bash_utils__print_info "${START_TEXT}"
    local platform=""

    case $(uname -m) in
    "x86_64")
        platform="x86_64"
        ;;

    "aarch64" | "arm64")
        platform="aarch64"
        ;;
    esac

    "${SCRIPT_DIR}/../dependencies/isaac_ros_common/scripts/build_image_layers.sh" \
        --image_key "${platform}.ros2_humble" \
        --image_name "isaac-ros-base"

    sfg_bash_utils__print_info "${END_TEXT}"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    sfg_isaac_ros_devcontainer__build_isaac_ros_base_image "${@}"
fi
