#!/usr/bin/env bash

sfg_agent_devcontainer__configure_project_as_service() {
    local devcontainer_user_directory="${1}"

    local SCRIPT_DIR
    SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)"
    source "${SCRIPT_DIR}/bash_utils/common"
    source "${SCRIPT_DIR}/get_project_name"

    local START_TEXT="> Configuring project as service."
    local END_TEXT="< Done configuring project as service."

    sfg_bash_utils__print_info "${START_TEXT}"

    if [[ ! -t 0 ]]; then
        sfg_bash_utils__print_plain "No terminal available for input. Skipping project service configuration."
        sfg_bash_utils__print_info "${END_TEXT}"
        return 0
    fi

    local SERVICE_TEMPLATE="${SCRIPT_DIR}/../config/service.template"
    local service_filename
    service_filename="$(sfg_agent_devcontainer__get_project_name).service"
    local service_filepath="${HOME}/.config/systemd/user/${service_filename}"
    mkdir -p "$(dirname "${service_filepath}")"

    local is_enabled
    is_enabled=$(systemctl --user is-enabled --quiet "${service_filename}" &>"/dev/null" && echo "true" || echo "false")
    local is_lingering
    is_lingering=$(loginctl show-user "$(whoami)" | grep -q "Linger=yes" && echo "true" || echo "false")

    if [[ "${is_enabled}" == "true" && "${is_lingering}" == "true" ]]; then
        local MESSAGE="The project is currently enabled to run as a service on system boot. Do you want to disable it? [y/N] "
        read -rp "${MESSAGE}" confirm

        if [[ ! "${confirm}" =~ ^[Yy]$ ]]; then
            sfg_bash_utils__print_info "${END_TEXT}"
            return 0
        fi

        systemctl --user disable "${service_filename}"
        rm "${service_filepath}"

        if [[ "${is_lingering}" == "true" ]]; then
            local message
            message="For the service to start on boot, linger was enabled for user $(whoami). Do you want to disable it? [y/N] "
            read -rp "${message}" confirm

            if [[ "${confirm}" =~ ^[Yy]$ ]]; then
                sudo loginctl disable-linger "$(whoami)"
            fi
        fi
    else
        local MESSAGE="The project is currently not enabled to run as a service on system boot. Do you want to enable it? [y/N] "
        read -rp "${MESSAGE}" confirm

        if [[ ! "${confirm}" =~ ^[Yy]$ ]]; then
            sfg_bash_utils__print_info "${END_TEXT}"
            return 0
        fi

        # shellcheck disable=SC2016
        PROJECT_NAME="$(sfg_agent_devcontainer__get_project_name)" WORKING_DIRECTORY="${devcontainer_user_directory}" envsubst '${PROJECT_NAME} ${WORKING_DIRECTORY}' <"${SERVICE_TEMPLATE}" >"${service_filepath}"
        systemctl --user daemon-reload
        systemctl --user enable "${service_filename}"

        if [[ "${is_lingering}" == "false" ]]; then
            sfg_bash_utils__print_plain "Enabling linger for user $(whoami)..."
            sudo loginctl enable-linger "$(whoami)"
        fi
    fi

    sfg_bash_utils__print_info "${END_TEXT}"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    set -e
    sfg_agent_devcontainer__configure_project_as_service "${@}"
fi
