#!/usr/bin/env bash

sfg_isaac_ros_devcontainer__configure_firewall() {
    local SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)
    source "${SCRIPT_DIR}/bash_utils/common"

    local START_TEXT="> Configuring firewall."
    local END_TEXT="< Done configuring firewall."

    sfg_bash_utils__print_info "${START_TEXT}"

    if ! command -v ufw &>"/dev/null"; then
        sfg_bash_utils__print_plain "No firewall is installed, nothing needs to be done."
        sfg_bash_utils__print_info "${END_TEXT}"
        return 0
    fi

    local MESSAGE="Firewall detected. Do you want to configure it? This requires sudo privileges. [y/N]"
    read -rp "${MESSAGE}" confirm

    if [[ ! "${confirm}" == y ]]; then
        sfg_bash_utils__print_info "${END_TEXT}"
        return 0
    fi

    # This allows ROS2 multicast traffic for discovery and communication.
    sudo ufw allow from 192.168.50.0/24
    sudo ufw reload
    sfg_bash_utils__print_info "${END_TEXT}"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    sfg_isaac_ros_devcontainer__configure_firewall "${@}"
fi
