#!/usr/bin/env bash

copy_build_dependencies() {
    local START_TEXT="> Copying build dependencies on host sy into the docker build context."
    local END_TEXT="< Done copying build dependencies on host system into the docker build context."

    print_info "${START_TEXT}"

    local build_dependencies=()

    case $(uname -m) in
    "x86_64") ;;

    "aarch64" | "arm64")
        build_dependencies+=(
            "/usr/src/jetson_multimedia_api"
            "$(realpath /usr/lib/aarch64-linux-gnu/tegra)"
        )
        ;;
    esac

    for build_dependency in "${build_dependencies[@]}"; do
        target_directory="${ISAAC_ROS_DEVCONTAINER_PROJECT_ROOT}/build_dependencies/$(basename "${build_dependency}")"

        if [ -d "${build_dependency}" ]; then
            print_plain "Copying build dependency '${build_dependency}'."
            rm -rf "${target_directory}" || true
            cp -r "${build_dependency}" "${target_directory}"
        else
            print_error "Error: Build dependency '${build_dependency}' does not exist."
            exit 1
        fi
    done

    print_info "${END_TEXT}"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)
    source "${SCRIPT_DIR}/common"
    copy_build_dependencies "${@}"
fi
