#!/usr/bin/env bash

sfg_agent_devcontainer__copy_dependencies() {
    local SCRIPT_DIR
    SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)"
    source "${SCRIPT_DIR}/bash_utils/common"
    source "${SCRIPT_DIR}/bash_utils/get_platform"

    local START_TEXT="> Copying dependencies on host system into the docker build context."
    local END_TEXT="< Done copying dependencies on host system into the docker build context."

    sfg_bash_utils__print_info "${START_TEXT}"
    local dependencies=()

    case $(sfg_bash_utils__get_platform) in
    "nvidia-jetson") ;;
    "nvidia") ;;
    "amd") ;;
    "generic") ;;
    esac

    for dependency in "${dependencies[@]}"; do
        target_directory="${SCRIPT_DIR}/../dependencies/$(basename "${dependency}")"

        if [ -d "${dependency}" ]; then
            sfg_bash_utils__print_plain "Copying build dependency '${dependency}'."
            rm -rf "${target_directory}" || true
            cp -r "${dependency}" "${target_directory}"
        else
            sfg_bash_utils__print_error "Error: Build dependency '${dependency}' does not exist."
            exit 1
        fi
    done

    sfg_bash_utils__print_info "${END_TEXT}"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    set -e
    sfg_agent_devcontainer__copy_dependencies "${@}"
fi
