#!/usr/bin/env bash
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)

source "${SCRIPT_DIR}/print_utils"

create_devcontainer_user_directory() {
    print_info "> Creating devcontainer user directory."
    DEVCONTAINER_USER_DIRECTORY="${SCRIPT_DIR}/../../.devcontainer-user"

    if [[ -d "${DEVCONTAINER_USER_DIRECTORY}" ]]; then
        print_error "Error: Devcontainer user directory already exists."
        exit 1
    fi

    mkdir -p "${DEVCONTAINER_USER_DIRECTORY}"
    echo ".env" >>"${DEVCONTAINER_USER_DIRECTORY}/.gitignore"
    echo \
        "include:
  - path:
      - \"../.devcontainer/compose/compose.base.yaml\"
      - \"../.devcontainer/compose/compose.\${PLATFORM}.yaml\"" >"${DEVCONTAINER_USER_DIRECTORY}/compose.yaml"
    echo "#!/usr/bin/env bash" >"${DEVCONTAINER_USER_DIRECTORY}/user_initialize_command"
    echo "#!/usr/bin/env bash" >"${DEVCONTAINER_USER_DIRECTORY}/user_install_dependencies"
    echo "#!/usr/bin/env bash" >"${DEVCONTAINER_USER_DIRECTORY}/user_post_start_command"
    chmod +x "${DEVCONTAINER_USER_DIRECTORY}/user_"*
    print_info "< Done creating devcontainer user directory."
}

create_devcontainer_user_directory
