#!/usr/bin/env bash

sfg_agent_devcontainer__cross_domain_router_entrypoint() {
    source "/opt/ros/${ROS_DISTRO}/setup.bash"
    echo "Starting Zenoh Router..."
    ros2 run rmw_zenoh_cpp rmw_zenohd &
    echo "Starting SFG Zenoh Domain Bridge..."
    sfg-zenoh-domain-bridge "${@}" &

    wait -n
    exit $?
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    set -e
    sfg_agent_devcontainer__cross_domain_router_entrypoint "${@}"
fi
