#!/usr/bin/env bash

sfg_isaac_ros_devcontainer__execute_user_post_start_command() {
    local SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)
    source "${SCRIPT_DIR}/bash_utils/common"

    local USER_POST_START_COMMAND="${REPOSITORY_DIRECTORY}/.devcontainer-user/user_post_start_command"
    local START_TEXT="> Executing user post start command '${USER_POST_START_COMMAND}'."
    local END_TEXT="< Done executing user post start command '${USER_POST_START_COMMAND}'."

    if [ -f "${USER_POST_START_COMMAND}" ]; then
        sfg_bash_utils__print_info "${START_TEXT}"
        "${USER_POST_START_COMMAND}"
        sfg_bash_utils__print_info "${END_TEXT}"
    fi
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    sfg_isaac_ros_devcontainer__execute_user_post_start_command "${@}"
fi
