#!/usr/bin/env bash

sfg_agent_devcontainer__execute_user_initialize_command() {
    local devcontainer_user_directory="${1}"

    local SCRIPT_DIR
    SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)"
    source "${SCRIPT_DIR}/bash_utils/common"

    local user_initialize_command="${devcontainer_user_directory}/user_initialize_command"

    local START_TEXT="> Executing user initialize command '${user_initialize_command}'."
    local END_TEXT="< Done executing user initialize command '${user_initialize_command}'."

    if [ -f "${user_initialize_command}" ]; then
        sfg_bash_utils__print_info "${START_TEXT}"
        "${user_initialize_command}" "${@}"
        sfg_bash_utils__print_info "${END_TEXT}"
    fi
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    set -e
    sfg_agent_devcontainer__execute_user_initialize_command "${@}"
fi
