#!/usr/bin/env bash

sfg_isaac_ros_devcontainer__execute_user_post_start_command() {
    local devcontainer_user_directory="${1}"

    local SCRIPT_DIR
    SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)"
    source "${SCRIPT_DIR}/bash_utils/common"
    local user_post_start_command="${devcontainer_user_directory}/user_post_start_command"

    local START_TEXT="> Executing user post start command '${user_post_start_command}'."
    local END_TEXT="< Done executing user post start command '${user_post_start_command}'."

    if [ -f "${user_post_start_command}" ]; then
        sfg_bash_utils__print_info "${START_TEXT}"
        "${user_post_start_command}"
        sfg_bash_utils__print_info "${END_TEXT}"
    fi
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    set -e
    sfg_isaac_ros_devcontainer__execute_user_post_start_command "${@}"
fi
