#!/usr/bin/env bash

forward_platform() {
    local environment_file="${1}"

    local START_TEXT="> Forwarding platform."
    local END_TEXT="< Done forwarding platform."

    print_info "${START_TEXT}"
    local platform=""

    case $(uname -m) in
    "x86_64")
        platform="amd64"
        ;;
    "aarch64" | "arm64")
        platform="arm64"
        ;;
    *)
        print_error "Unsupported platform: $(uname -m)" >&2
        exit 1
        ;;
    esac

    print_plain "Detected platform '${platform}'."
    set_environment_variable "${environment_file}" "PLATFORM" "${platform}"
    print_info "${END_TEXT}"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)
    source "${SCRIPT_DIR}/common"
    forward_jtop_gid "${@}"
fi
