#!/usr/bin/env bash

sfg_isaac_ros_devcontainer__forward_project_name() {
    local environment_file="${1}"

    local SCRIPT_DIR
    SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)"
    source "${SCRIPT_DIR}/bash_utils/common"
    source "${SCRIPT_DIR}/get_project_name"

    local START_TEXT="> Forwarding project name."
    local END_TEXT="< Done forwarding project name."

    sfg_bash_utils__print_info "${START_TEXT}"
    sfg_bash_utils__set_environment_variable "${environment_file}" "PROJECT_NAME" "$(sfg_isaac_ros_devcontainer__get_project_name)"
    sfg_bash_utils__print_info "${END_TEXT}"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    set -e
    sfg_isaac_ros_devcontainer__forward_project_name "${@}"
fi
