#!/usr/bin/env bash

sfg_isaac_ros_devcontainer__forward_jtop_gid() {
    local environment_file="${1}"

    local SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)
    source "${SCRIPT_DIR}/bash_utils/common"

    local START_TEXT="> Forwarding jtop GID."
    local END_TEXT="< Done forwarding jtop GID."

    sfg_bash_utils__print_info "${START_TEXT}"

    if [ -S "/run/jtop.sock" ]; then
        sfg_bash_utils__set_environment_variable "${environment_file}" "LOCAL_JTOP_GID" "$(stat -c %g /run/jtop.sock)"
    else
        sfg_bash_utils__print_warning "Could not find jtop socket. If you are running on a jetson platform you should install 'https://github.com/rbonghi/jetson_stats'."
    fi

    sfg_bash_utils__print_info "${END_TEXT}"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    sfg_isaac_ros_devcontainer__forward_jtop_gid "${@}"
fi
