#!/usr/bin/env bash

forward_environment_variables() {
    local environment_file="${1}"

    local START_TEXT="> Forwarding environment variables."
    local END_TEXT="< Done forwarding environment variables."

    print_info "${START_TEXT}"

    for var in "${@:2}"; do
        # Extract variable name (before '=').
        local environment_variable=${var%%=*}
        # Extract variable value (after '=').
        local value=${var#*=}

        print_plain "Forwarding environment variable '${var}'."
        set_environment_variable "${environment_file}" "${environment_variable}" "${value}"
    done

    print_info "${END_TEXT}"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)
    source "${SCRIPT_DIR}/common"
    forward_environment_variables "${@}"
fi
