#!/usr/bin/env bash

forward_user() {
    local environment_file="${1}"

    local START_TEXT="> Forwarding user."
    local END_TEXT="< Done forwarding user."

    print_info "${START_TEXT}"
    local username="${USER}"
    local user_uid=$(id -u "${USER}")
    local user_gid=$(id -g "${USER}")

    print_plain "Forwarding username '${username}'."
    set_environment_variable "${environment_file}" "LOCAL_USERNAME" "${username}"

    print_plain "Forwarding UID '${user_uid}'."
    set_environment_variable "${environment_file}" "LOCAL_USER_UID" "${user_uid}"

    print_plain "Forwarding GID '${user_gid}'."
    set_environment_variable "${environment_file}" "LOCAL_USER_GID" "${user_gid}"

    print_info "${END_TEXT}"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)
    source "${SCRIPT_DIR}/common"
    forward_user "${@}"
fi
