#!/usr/bin/env bash
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)

source "${SCRIPT_DIR}/env_file_utils"
source "${SCRIPT_DIR}/print_utils"

local_workspace_directory="${1#*=}"
container_workspace_directory="${2#*=}"
ENVIRONMENT_FILE="${SCRIPT_DIR}/../../.devcontainer-user/.env"

set_up_mounted_directory() {
    local START_TEXT="> Setting up a directory to be mounted inside the dev container."
    local END_TEXT="< Done setting up a directory to be mounted inside the dev container."

    print_info "${START_TEXT}"
    print_plain "Set up a directory to be mounted inside the dev container."
    print_warning "Note that if you change the directory to be mounted, you will need to rebuild the container for the changes to take effect."

    local ENVIRONMENT_VARIABLE="LOCAL_SELECTED_DIRECTORY"
    local value=$(get_environment_variable "${ENVIRONMENT_FILE}" "${ENVIRONMENT_VARIABLE}")

    if [[ -n "${value}" && -d "${value}" ]]; then
        local MESSAGE="The directory '${value}' has previously been selected for mounting. Would you like to choose a different directory? [y/N] "
        read -rp "${MESSAGE}" confirm

        if [[ ! "${confirm}" == y ]]; then
            set_environment_variable "${ENVIRONMENT_FILE}" "CONTAINER_SELECTED_DIRECTORY_MOUNT_POINT" "${container_workspace_directory}/$(basename "${value}")"
            print_info "${END_TEXT}"
            return
        fi
    fi

    # Allow the developer to choose a directory of their choice to mount.
    read -rp "Enter a directory to mount: " value

    # Check if the user canceled directory selection.
    if [[ -z "${value}" ]]; then
        print_info "Error: Directory selection canceled."
        exit 1
    fi

    # Check if the provided directory exists.
    if [[ ! -d "${value}" ]]; then
        print_error "Error: The directory does not exist."
        exit 1
    fi

    # Save the selected directory in an environment variable. This will later be leveraged
    # by docker compose to mount the specified directory inside the container.
    set_environment_variable "${ENVIRONMENT_FILE}" "${ENVIRONMENT_VARIABLE}" "${value}"
    set_environment_variable "${ENVIRONMENT_FILE}" "CONTAINER_SELECTED_DIRECTORY_MOUNT_POINT" "${container_workspace_directory}/$(basename "${value}")"
    print_info "${END_TEXT}"
}

configure_ros_domain_id() {
    local START_TEXT="> Configure ROS domain ID."
    local END_TEXT="< Done configuring ROS domain ID."

    print_info "${START_TEXT}"

    local ENVIRONMENT_VARIABLE="ROS_DOMAIN_ID"
    local value=$(get_environment_variable "${ENVIRONMENT_FILE}" "${ENVIRONMENT_VARIABLE}")

    if [[ -n "${value}" ]]; then
        local MESSAGE="ROS domain ID '${value}' is already set. Would you like to configure a different domain ID? [y/N] "
        read -rp "${MESSAGE}" confirm

        if [[ ! "${confirm}" == y ]]; then
            print_info "${END_TEXT}"
            return
        fi
    fi

    # Ask the user for a domain ID.
    read -rp "Enter a ROS domain ID in the range [1-101] or [215-232]: " value

    # Validate input.
    if [[ -z "${value}" ]]; then
        print_error "Error: ROS domain ID configuration canceled."
        exit 1
    fi

    if ! [[ "${value}" =~ ^[0-9]+$ ]]; then
        print_error "Error: Invalid input. Please enter an integer."
        exit 1
    fi

    if ! { [[ "${value}" -ge 1 && "${value}" -le 101 ]] || [[ "${value}" -ge 215 && "${value}" -le 232 ]]; }; then
        print_error "Error: ROS domain ID must be between 1-101 or 215-232."
        exit 1
    fi

    # Save the chosen ROS domain ID.
    set_environment_variable "${ENVIRONMENT_FILE}" "${ENVIRONMENT_VARIABLE}" "${value}"
    print_info "${END_TEXT}"
}

setup_repository() {
    local START_TEXT="> Setting up repository inside container."
    local END_TEXT="< Done setting up repository inside container."

    print_info "${START_TEXT}"
    set_environment_variable "${ENVIRONMENT_FILE}" "CONTAINER_REPOSITORY_MOUNT_POINT" "${container_workspace_directory}/$(basename "${local_workspace_directory}")"
    print_info "${END_TEXT}"
}

setup_ntp_client() {
    local START_TEXT="> Setting up NTP client."
    local END_TEXT="< Done setting up NTP client."

    print_info "${START_TEXT}"

    if ! systemctl is-enabled systemd-timesyncd.service &>"/dev/null"; then
        print_error "Error: NTP client setup requires service systemd-timesyncd. You need to install and enable it with 'sudo systemctl enable --now systemd-timesyncd'."
        exit 1
    fi

    local changes_made=false

    local CONFIG_FILE="/etc/systemd/timesyncd.conf"
    local NTP_SERVER="192.168.50.1"
    local FALLBACK_NTP_SERVER="ntp.ubuntu.com"
    local SED_EXPRESSION=(
        -e '/^NTP=.*/d'
        -e '/^FallbackNTP=.*/d'
        -e "/^\[Time\]/a NTP=${NTP_SERVER}\nFallbackNTP=${FALLBACK_NTP_SERVER}"
    )

    if ! sed "${SED_EXPRESSION[@]}" "${CONFIG_FILE}" | diff -q - "${CONFIG_FILE}" >"/dev/null"; then
        print_plain "NTP server configuration requires changes. Updating..."
        sudo sed -i "${SED_EXPRESSION[@]}" "${CONFIG_FILE}"
        changes_made=true
    fi

    if ! timedatectl | grep -q 'NTP service: active'; then
        print_plain "NTP service is not active. Enabling..."
        timedatectl set-ntp true
        changes_made=true
    fi

    if [ "${changes_made}" = true ]; then
        print_info "Configuration changed. Restarting systemd-timesyncd service..."
        sudo systemctl restart systemd-timesyncd
    else
        print_plain "No changes were necessary."
    fi

    print_info "${END_TEXT}"
}

forward_environment_variables() {
    local START_TEXT="> Forwarding environment variables."
    local END_TEXT="< Done forwarding environment variables."

    print_info "${START_TEXT}"

    for var in "${@}"; do
        # Extract variable name (before '=').
        local environment_variable=${var%%=*}
        # Extract variable value (after '=').
        local value=${var#*=}

        print_plain "Forwarding environment variable '${var}' to the container."
        set_environment_variable "${ENVIRONMENT_FILE}" "${environment_variable}" "${value}"
    done

    print_info "${END_TEXT}"
}

forward_user() {
    local START_TEXT="> Forwarding user."
    local END_TEXT="< Done forwarding user."

    print_info "${START_TEXT}"

    local username="${USER}"
    local user_uid=$(id -u "${USER}")
    local user_gid=$(id -g "${USER}")

    print_plain "Forwarding username '${username}'."
    set_environment_variable "${ENVIRONMENT_FILE}" "LOCAL_USERNAME" "${username}"

    print_plain "Forwarding UID '${user_uid}'."
    set_environment_variable "${ENVIRONMENT_FILE}" "LOCAL_USER_UID" "${user_uid}"

    print_plain "Forwarding GID '${user_gid}'."
    set_environment_variable "${ENVIRONMENT_FILE}" "LOCAL_USER_GID" "${user_gid}"

    print_info "${END_TEXT}"
}

forward_platform() {
    local START_TEXT="> Forwarding platform."
    local END_TEXT="< Done forwarding platform."

    print_info "${START_TEXT}"
    local platform=""

    case $(uname -m) in
    "x86_64")
        platform="amd64"
        ;;
    "aarch64" | "arm64")
        platform="arm64"
        ;;
    *)
        print_error "Unsupported platform: $(uname -m)" >&2
        exit 1
        ;;
    esac

    print_plain "Detected platform '${platform}'."
    set_environment_variable "${ENVIRONMENT_FILE}" "PLATFORM" "${platform}"
    print_info "${END_TEXT}"
}

forward_jtop_gid() {
    local START_TEXT="> Forwarding jtop GID."
    local END_TEXT="< Done forwarding jtop GID."

    print_info "${START_TEXT}"

    if [ -S "/run/jtop.sock" ]; then
        set_environment_variable "${ENVIRONMENT_FILE}" "LOCAL_JTOP_GID" "$(stat -c %g /run/jtop.sock)"
    else
        print_warning "Could not find jtop socket. If you are running on a jetson platform you should install 'https://github.com/rbonghi/jetson_stats'."
    fi

    print_info "${END_TEXT}"
}

copy_build_dependencies() {
    local START_TEXT="> Copying build dependencies on host sy into the docker build context."
    local END_TEXT="< Done copying build dependencies on host system into the docker build context."

    print_info "${START_TEXT}"

    local build_dependencies=()

    case $(uname -m) in
    "x86_64") ;;

    "aarch64" | "arm64")
        build_dependencies+=(
            "/usr/src/jetson_multimedia_api"
            "$(realpath /usr/lib/aarch64-linux-gnu/tegra)"
        )
        ;;
    esac

    for build_dependency in "${build_dependencies[@]}"; do
        target_directory="${SCRIPT_DIR}/../build_dependencies/$(basename "${build_dependency}")"

        if [ -d "${build_dependency}" ]; then
            print_plain "Copying build dependency '${build_dependency}'."
            rm -rf "${target_directory}" || true
            cp -r "${build_dependency}" "${target_directory}"
        else
            print_error "Error: Build dependency '${build_dependency}' does not exist."
            exit 1
        fi
    done

    print_info "${END_TEXT}"
}

execute_user_initialize_command() {
    local USER_INITIALIZE_COMMAND="${local_workspace_directory}/.devcontainer-user/user_initialize_command"
    local START_TEXT="> Executing user initialize command '${USER_INITIALIZE_COMMAND}'."
    local END_TEXT="< Done executing user initialize command '${USER_INITIALIZE_COMMAND}'."

    if [ -f "${USER_INITIALIZE_COMMAND}" ]; then
        print_info "${START_TEXT}"
        "${USER_INITIALIZE_COMMAND}" "${@}"
        print_info "${END_TEXT}"
    fi
}

build_isaac_ros_base_image() {
    local START_TEXT="> Building Isaac ROS base image."
    local END_TEXT="< Done building Isaac ROS base image."

    print_info "${START_TEXT}"
    local image_key=""

    case $(uname -m) in
    "x86_64")
        image_key="x86_64"
        ;;

    "aarch64" | "arm64")
        image_key="aarch64"
        ;;
    esac

    "${SCRIPT_DIR}/../build_dependencies/isaac_ros_common/scripts/build_image_layers.sh" \
        --image_key "${image_key} ros2_humble" \
        --image_name "isaac-ros-base"

    print_info "${END_TEXT}"
}

instantiate_isaac_ros_dockerfile_template() {
    local START_TEXT="> Instantiating Isaac ROS dockerfile template."
    local END_TEXT="< Done instantiating Isaac ROS dockerfile template."

    print_info "${START_TEXT}"

    local DOCKERFILE_TEMPLATE="${SCRIPT_DIR}/../resources/isaac_ros.dockerfile.template"
    local DOCKERFILE_USER="${local_workspace_directory}/.devcontainer-user/dockerfile"
    local DOCKERFILE="${SCRIPT_DIR}/../docker/isaac_ros.dockerfile"

    if [ -f "${DOCKERFILE_USER}" ]; then
        sed -e "/:DOCKERFILE_USER:/{r ${DOCKERFILE_USER}" -e "d}" "${DOCKERFILE_TEMPLATE}" >"${DOCKERFILE}"
    else
        sed -e "/:DOCKERFILE_USER:/d" "${DOCKERFILE_TEMPLATE}" >"${DOCKERFILE}"
    fi

    print_info "${END_TEXT}"
}

print_plain ""
set_up_mounted_directory
configure_ros_domain_id
setup_repository
setup_ntp_client
forward_environment_variables "${@}"
forward_user
forward_platform
forward_jtop_gid
copy_build_dependencies
execute_user_initialize_command "${@}"
build_isaac_ros_base_image
instantiate_isaac_ros_dockerfile_template
