#!/usr/bin/env bash
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)

source "${SCRIPT_DIR}/env_file_utils"
source "${SCRIPT_DIR}/print_utils"

LOCAL_WORKSPACE_DIRECTORY="${1#*=}"
CONTAINTER_WORKSPACE_DIRECTORY="${2#*=}"
ENVIRONMENT_FILE="${LOCAL_WORKSPACE_DIRECTORY}/.devcontainer-user/.env"

set_up_mounted_directory() {
  print_info "> Set up a directory to be mounted inside the dev container."
  print_warning "Note that if you change the directory to be mounted, you will need to rebuild the container for the changes to take effect."

  local ENVIRONMENT_VARIABLE="LOCAL_SELECTED_DIRECTORY"
  local value=$(get_environment_variable "${ENVIRONMENT_FILE}" "LOCAL_SELECTED_DIRECTORY")

  if [[ ! -z "${value}" && -d "${value}" ]]; then
    local MESSAGE="The directory '${value}' has previously been selected for mounting. Would you like to choose a different directory? [y/N] "
    read -p "${MESSAGE}" CONFIRM

    if [[ ! $CONFIRM == y ]]; then
      set_environment_variable "${ENVIRONMENT_FILE}" "CONTAINER_SELECTED_DIRECTORY_MOUNT_POINT" "${CONTAINTER_WORKSPACE_DIRECTORY}/$(basename ${value})"
      print_info "< Done setting up a directory to be mounted inside the dev container."
      return
    fi
  fi

  # Allow the developer to choose a directory of their choice to mount.
  read -p "Enter a directory to mount: " value

  # Check if the user canceled directory selection.
  if [[ -z "${value}" ]]; then
    print_info "Error: Directory selection canceled."
    exit 1
  fi

  # Check if the provided directory exists.
  if [[ ! -d "${value}" ]]; then
    print_error "Error: The directory does not exist."
    exit 1
  fi

  # Save the selected directory in an environment variable. This will later be leveraged
  # by docker compose to mount the specified directory inside the container.
  set_environment_variable "${ENVIRONMENT_FILE}" "LOCAL_SELECTED_DIRECTORY" "${value}"
  set_environment_variable "${ENVIRONMENT_FILE}" "CONTAINER_SELECTED_DIRECTORY_MOUNT_POINT" "${CONTAINTER_WORKSPACE_DIRECTORY}/$(basename ${value})"
  print_info "< Done setting up a directory to be mounted inside the dev container."
}

configure_ros_domain_id() {
  print_info "> Configure ROS domain ID."

  local ENVIRONMENT_VARIABLE="ROS_DOMAIN_ID"
  local value=$(get_environment_variable "${ENVIRONMENT_FILE}" "${ENVIRONMENT_VARIABLE}")

  if [[ ! -z "${value}" ]]; then
    local MESSAGE="ROS domain ID '${value}' is already set. Would you like to configure a different domain ID? [y/N] "
    read -p "${MESSAGE}" CONFIRM

    if [[ ! $CONFIRM == y ]]; then
      print_info "< Done configuring ROS domain ID."
      return
    fi
  fi

  # Ask the user for a domain ID.
  read -p "Enter a ROS domain ID in the range [1-101] or [215-232]: " value

  # Validate input.
  if [[ -z "${value}" ]]; then
    print_error "Error: ROS domain ID configuration canceled."
    exit 1
  fi

  if ! [[ "${value}" =~ ^[0-9]+$ ]]; then
    print_error "Error: Invalid input. Please enter an integer."
    exit 1
  fi

  if ! { [[ "${value}" -ge 1 && "${value}" -le 101 ]] || [[ "${value}" -ge 215 && "${value}" -le 232 ]]; }; then
    print_error "Error: ROS domain ID must be between 1-101 or 215-232."
    exit 1
  fi

  # Save the chosen ROS domain ID.
  set_environment_variable "${ENVIRONMENT_FILE}" "${ENVIRONMENT_VARIABLE}" "${value}"
  print_info "< Done configuring ROS domain ID."
}

setup_repository() {
  print_info "> Set up repository inside container."
  set_environment_variable "${ENVIRONMENT_FILE}" "CONTAINER_REPOSITORY_MOUNT_POINT" "${CONTAINTER_WORKSPACE_DIRECTORY}/$(basename ${LOCAL_WORKSPACE_DIRECTORY})"
  print_info "< Done setting up repository inside container."
}

forward_environment_variables() {
  print_info "> Forwarding environment variables."

  for VAR in "${@}"; do
    # Extract variable name (before '=').
    local ENVIRONMENT_VARIABLE=${VAR%%=*}
    # Extract variable value (after '=').
    local VALUE=${VAR#*=}

    set_environment_variable "${ENVIRONMENT_FILE}" "${ENVIRONMENT_VARIABLE}" "${VALUE}"
  done

  print_info "< Done forwarding environment variables."
}

forward_user() {
  print_info "> Forwarding user."
  set_environment_variable "${ENVIRONMENT_FILE}" "LOCAL_USERNAME" "${USER}"
  set_environment_variable "${ENVIRONMENT_FILE}" "LOCAL_USER_UID" "$(id -u ${USER})"
  set_environment_variable "${ENVIRONMENT_FILE}" "LOCAL_USER_GID" "$(id -g ${USER})"
  print_info "< Done forwarding user."
}

forward_platform() {
  print_info "> Forwarding platform."

  case $(uname -m) in
  "x86_64")
    PLATFORM="amd64"
    ;;
  "aarch64" | "arm64")
    PLATFORM="arm64"
    ;;
  *)
    print_error "Unsupported architecture: $(uname -m)" >&2
    exit 1
    ;;
  esac

  set_environment_variable "${ENVIRONMENT_FILE}" "PLATFORM" "${PLATFORM}"
  print_info "< Done forwarding platform."
}

forward_jtop_gid() {
  print_info "> Forwarding jtop GID."

  if [ -S "/run/jtop.sock" ]; then
    set_environment_variable "${ENVIRONMENT_FILE}" "LOCAL_JTOP_GID" "$(stat -c %g /run/jtop.sock)"
  fi

  print_info "< Done forwarding jtop GID."
}

execute_user_initialize_command() {
  USER_INITIALIZE_COMMAND="${LOCAL_WORKSPACE_DIRECTORY}/.devcontainer-user/user_initialize_command"

  if [ -f "${USER_INITIALIZE_COMMAND}" ]; then
    print_info "> Executing user initialize command '${USER_INITIALIZE_COMMAND}'."
    "${USER_INITIALIZE_COMMAND}" ${@}
    print_info "< Done executing user initialize command '${USER_INITIALIZE_COMMAND}'."
  fi
}

print_plain ""
set_up_mounted_directory
configure_ros_domain_id
setup_repository
forward_environment_variables ${@}
forward_user
forward_platform
forward_jtop_gid
execute_user_initialize_command ${@}
