#!/usr/bin/env bash

sfg_isaac_ros_devcontainer__instantiate_isaac_ros_dockerfile_template() {
    local devcontainer_user_directory="${1}"

    local SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)
    source "${SCRIPT_DIR}/bash_utils/common"

    local START_TEXT="> Instantiating Isaac ROS dockerfile template."
    local END_TEXT="< Done instantiating Isaac ROS dockerfile template."

    sfg_bash_utils__print_info "${START_TEXT}"
    local DOCKERFILE_TEMPLATE="${SCRIPT_DIR}/../resources/dockerfile.isaac_ros.template"
    local dockerfile_user="${devcontainer_user_directory}/dockerfile.user"
    local DOCKERFILE="${SCRIPT_DIR}/../docker/dockerfile.isaac_ros"

    if [ -f "${dockerfile_user}" ]; then
        sed -e "/:DOCKERFILE_USER:/{r ${dockerfile_user}" -e "d}" "${DOCKERFILE_TEMPLATE}" >"${DOCKERFILE}"
    else
        sed -e "/:DOCKERFILE_USER:/d" "${DOCKERFILE_TEMPLATE}" >"${DOCKERFILE}"
    fi

    sfg_bash_utils__print_info "${END_TEXT}"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    sfg_isaac_ros_devcontainer__instantiate_isaac_ros_dockerfile_template "${@}"
fi
