#!/usr/bin/env bash

sfg_isaac_ros_devcontainer__post_start_command() {
    local SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)
    source "${SCRIPT_DIR}/bash_utils/common"
    source "${SCRIPT_DIR}/execute_user_post_start_command"

    sfg_isaac_ros_devcontainer__execute_user_post_start_command "${@}"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    sfg_isaac_ros_devcontainer__post_start_command "${@}"
fi
