#!/usr/bin/env bash
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)

source "${SCRIPT_DIR}/print_utils"

execute_user_post_start_command() {
    USER_POST_START_COMMAND="${REPOSITORY_DIRECTORY}/.devcontainer-user/user_post_start_command"

    if [ -f "${USER_POST_START_COMMAND}" ]; then
        print_info "> Executing user post start command '${USER_POST_START_COMMAND}'."
        "${USER_POST_START_COMMAND}"
        print_info "< Done executing user post start command '${USER_POST_START_COMMAND}'."
    fi
}

print_plain ""
execute_user_post_start_command
