#!/usr/bin/env bash

setup_repository() {
    local environment_file="${1}"
    local local_workspace_directory="${2}"
    local container_workspace_directory="${3}"

    local START_TEXT="> Setting up repository inside container."
    local END_TEXT="< Done setting up repository inside container."

    print_info "${START_TEXT}"
    set_environment_variable "${environment_file}" "CONTAINER_REPOSITORY_MOUNT_POINT" "${container_workspace_directory}/$(basename "${local_workspace_directory}")"
    print_info "${END_TEXT}"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)
    source "${SCRIPT_DIR}/common"
    setup_repository "${@}"
fi
