#!/usr/bin/env bash

set_up_mounted_directory() {
    local environment_file="${1}"
    local container_workspace_directory="${2}"

    local START_TEXT="> Setting up a directory to be mounted inside the dev container."
    local END_TEXT="< Done setting up a directory to be mounted inside the dev container."

    print_info "${START_TEXT}"
    print_plain "Set up a directory to be mounted inside the dev container."
    print_warning "Note that if you change the directory to be mounted, you will need to rebuild the container for the changes to take effect."

    local ENVIRONMENT_VARIABLE="LOCAL_SELECTED_DIRECTORY"
    local value=$(get_environment_variable "${environment_file}" "${ENVIRONMENT_VARIABLE}")

    if [[ -n "${value}" && -d "${value}" ]]; then
        local MESSAGE="The directory '${value}' has previously been selected for mounting. Would you like to choose a different directory? [y/N] "
        read -rp "${MESSAGE}" confirm

        if [[ ! "${confirm}" == y ]]; then
            set_environment_variable "${environment_file}" "CONTAINER_SELECTED_DIRECTORY_MOUNT_POINT" "${container_workspace_directory}/$(basename "${value}")"
            print_info "${END_TEXT}"
            return
        fi
    fi

    # Allow the developer to choose a directory of their choice to mount.
    read -rp "Enter a directory to mount: " value

    # Check if the user canceled directory selection.
    if [[ -z "${value}" ]]; then
        print_error "Error: Directory selection canceled."
        exit 1
    fi

    # Check if the provided directory exists.
    if [[ ! -d "${value}" ]]; then
        print_error "Error: The directory does not exist."
        exit 1
    fi

    # Save the selected directory in an environment variable. This will later be leveraged
    # by docker compose to mount the specified directory inside the container.
    set_environment_variable "${environment_file}" "${ENVIRONMENT_VARIABLE}" "${value}"
    set_environment_variable "${environment_file}" "CONTAINER_SELECTED_DIRECTORY_MOUNT_POINT" "${container_workspace_directory}/$(basename "${value}")"
    print_info "${END_TEXT}"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)
    source "${SCRIPT_DIR}/common"
    set_up_mounted_directory "${@}"
fi
