#!/usr/bin/env bash

sfg_isaac_ros_devcontainer__stop_project_service() {
    local SCRIPT_DIR
    SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)"
    source "${SCRIPT_DIR}/bash_utils/common"
    source "${SCRIPT_DIR}/get_project_name"

    local service_name
    service_name="$(sfg_isaac_ros_devcontainer__get_project_name)"

    local START_TEXT="> Stopping service ${service_name}."
    local END_TEXT="< Done stopping service ${service_name}."

    if systemctl --user is-active --quiet "${service_name}"; then
        sfg_bash_utils__print_info "${START_TEXT}"
        systemctl --user stop "${service_name}"
        sfg_bash_utils__print_info "${END_TEXT}"
    fi
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    set -e
    sfg_isaac_ros_devcontainer__stop_project_service "${@}"
fi
